#!/bin/sh

WALLPAPERS="$HOME/Universe Sandbox/Images"
feh --bg-scale -z "$WALLPAPERS"

trayer --edge top --align right --widthtype request --expand true \
    --SetDockType true --SetPartialStrut true --transparent true --alpha 0 \
    --tint 0x1A1918 --expand true --heighttype pixel --height 32 --padding 1 \
    --widthtype pixel --width 120 --monitor 1 &

setxkbmap -layout pl
xscreensaver
